version: '3.5'

services:
  nac-admin:
    image: nac-admin
    build:
      context: .
      dockerfile: ./dockerfile-dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      -  '80:3000'